/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RiddlesRouteImport } from "./routes/riddles"
import { Route as JokesRouteImport } from "./routes/jokes"
import { Route as IndexRouteImport } from "./routes/index"

const RiddlesRoute = RiddlesRouteImport.update({
  id: "/riddles",
  path: "/riddles",
  getParentRoute: () => rootRouteImport,
} as any)
const JokesRoute = JokesRouteImport.update({
  id: "/jokes",
  path: "/jokes",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/jokes": typeof JokesRoute
  "/riddles": typeof RiddlesRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/jokes": typeof JokesRoute
  "/riddles": typeof RiddlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/jokes": typeof JokesRoute
  "/riddles": typeof RiddlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/jokes" | "/riddles"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/jokes" | "/riddles"
  id: "__root__" | "/" | "/jokes" | "/riddles"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JokesRoute: typeof JokesRoute
  RiddlesRoute: typeof RiddlesRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/riddles": {
      id: "/riddles"
      path: "/riddles"
      fullPath: "/riddles"
      preLoaderRoute: typeof RiddlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/jokes": {
      id: "/jokes"
      path: "/jokes"
      fullPath: "/jokes"
      preLoaderRoute: typeof JokesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JokesRoute: JokesRoute,
  RiddlesRoute: RiddlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
